function importfile_spikes(fileToRead1,varname)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 12-Jun-2013 12:20:41

DELIMITER = '\t';
HEADERLINES = 4;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
assignin('base', varname, newData1.('data'));


