function read_roj(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 26-Jun-2013 17:34:57

DELIMITER = ' ';
HEADERLINES = 4;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.

rg=regexp(fileToRead1,'datos00','split');
varname=['syn' rg{2}(1:2)];
 
eval([ varname '= newData1.data;']);
save(varname, varname);

